services:
  web:
    build: .
    container_name: multimodal_flask
    env_file:
      - .env
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: multimodal_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
